apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-court-data-adaptor.fullname" . }}
  labels:
{{ include "laa-court-data-adaptor.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "laa-court-data-adaptor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "laa-court-data-adaptor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "laa-court-data-adaptor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: laa-court-data-adaptor-instance-output
                  key: url
            - name: SECRET_KEY_BASE
              value: {{ .Values.rails.secret_key_base }}
            - name: COMMON_PLATFORM_URL
              value: {{ .Values.common_platform_url }}
            - name: SHARED_SECRET_KEY
              value: {{ .Values.common_platform_secret_key }}
            {{- if .Values.mtls_enabled }}
            - name: SSL_CLIENT_CERT
              value: |
                {{ .Files.Get .Values.ssl_cert_file | b64enc }}
            - name: SSL_CLIENT_KEY
              value: |
                {{ .Files.Get .Values.ssl_key_file | b64enc }}
            {{- end }}
            {{- if .Values.sqs_messaging_enabled }}
            - name: AWS_LINK_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: cda-messaging-queues-output
                  key: sqs_url_link
            - name: AWS_UNLINK_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: cda-messaging-queues-output
                  key: sqs_url_unlink
            - name: AWS_HEARING_RESULTED_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: cda-messaging-queues-output
                  key: sqs_url_hearing_resulted
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cda-messaging-queues-output
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cda-messaging-queues-output
                  key: secret_access_key
            {{- end }}
            - name: AWS_REGION
              value: {{ .Values.sqs_region }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
